# Execute your favorite apps at launch

exec-once = waypaper --restore
exec-once = wal -R
# exec-once = hypridle
exec-once = xwaylandvideobridge
# exec-once = copyq --start-server
exec-once = waybar
exec-once = hyprpanel
exec-once = swww-daemon
# exec-once = nm-applet --indicator
# exec-once = blueman-applet
# exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
# exec-once = swaync