hl.on("hyprland.start", function()
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("wal -R")
    -- hl.exec_cmd("hypridle")
    hl.exec_cmd("xwaylandvideobridge")
    -- hl.exec_cmd("copyq --start-server")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("waybar")
    -- hl.exec_cmd("hyprpanel")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("~/.config/wvkbd/launch.sh")
    -- hl.exec_cmd("nm-applet --indicator")
    -- hl.exec_cmd("blueman-applet")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
