# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vfr = true # Variable refresh rate, set to false to disable it. It can cause stuttering on some monitors, but it can also reduce input latency and save power on others.
}

render {
    direct_scanout = true # Set to false to disable direct scanout, which can cause stuttering on some monitors, but it can also reduce input latency and save power on others.
}