# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Rofi Dynamic Island effect
layerrule = blur on, ignore_alpha 0.5, animation slide, match:namespace rofi

layerrule = blur on, ignore_alpha 0.5, match:namespace waybar

#Swaync
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-notification-window

windowrule = float on, size (monitor_w*0.6) (monitor_h*0.4), match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class nmtui
windowrule = no_blur on, match:class firefox
windowrule = no_blur on, match:class Code
windowrule = float on, match:class jetbrains-studio
windowrule = float on, match:class Emulator

windowrule = float on, match:class steam
windowrule = float on, match:class steam, match:title Friends List
windowrule = workspace 1, match:class cs2
windowrule = workspace 1, match:class steam_app_2352620, match:title fellowship
windowrule = workspace 2 silent, match:class discord
windowrule = workspace 3 silent, match:class elecwhat
windowrule = float on, match:class me.kavishdevar.librepods
# windowrulev2 = float, class:Alacritty
windowrule = suppress_event maximize, match:class .* # You'll probably like this.